server:
  port: 8083
openapi:
  universalResolver:
    base-path: /metadata-coordinator
  trustedIssuerRegistry:
    base-path: /metadata-coordinator
coordinator:
  logging:
    level: debug

trustedIssuerRegistry:
  base-path: http://localhost:8082/trusted-issuer-registry/registry
didWebResolver:
  base-path: http://localhost:8081/did-web-resolver/identifiers
